/*******************************************************************************
 * Copyright 2012-present Pixate, Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
/* The following code was generated by JFlex 1.4.3 on 7/3/13 4:23 PM */

package com.pixate.freestyle.cg.parsing;

import java.io.Reader;
import java.io.StringReader;

import com.pixate.freestyle.cg.math.PXDimension;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 7/3/13 4:23 PM from the specification file
 * <tt>Transforms.flex</tt>
 */
class PXTransformLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\4\1\0\2\4\22\0\1\4\4\0\1\31\2\0"+
    "\1\32\1\33\1\0\1\1\1\34\1\1\1\3\1\0\12\2\7\0"+
    "\1\7\1\0\1\16\1\25\1\13\1\0\1\26\1\27\1\23\1\0"+
    "\1\17\1\12\1\22\1\10\1\21\1\24\1\0\1\6\1\11\1\5"+
    "\2\0\1\20\1\14\1\15\1\30\6\0\1\7\1\0\1\16\1\25"+
    "\1\13\1\0\1\26\1\27\1\23\1\0\1\17\1\12\1\22\1\10"+
    "\1\21\1\24\1\0\1\6\1\11\1\5\2\0\1\20\1\14\1\15"+
    "\1\30\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\1\1\3\4\1\1\4\1\5"+
    "\1\6\2\0\1\7\11\0\1\10\1\2\6\0\1\11"+
    "\1\12\1\13\1\0\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\3\0\1\22\5\0\1\23\1\24\1\25\1\26"+
    "\4\0\1\27\1\0\1\30\2\0\1\31\1\32\1\33"+
    "\2\0\1\34\1\35\1\36\1\37\2\0\1\40\1\41"+
    "\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\35\0\72\0\127\0\164\0\221\0\256\0\313"+
    "\0\350\0\u0105\0\35\0\35\0\35\0\164\0\u0122\0\35"+
    "\0\u013f\0\u015c\0\u0179\0\u0196\0\u01b3\0\u01d0\0\u01ed\0\u020a"+
    "\0\u0227\0\35\0\u0244\0\u0261\0\u027e\0\u029b\0\u02b8\0\u02d5"+
    "\0\u02f2\0\35\0\35\0\35\0\u030f\0\35\0\35\0\35"+
    "\0\35\0\35\0\35\0\u032c\0\u0349\0\u0366\0\35\0\u0383"+
    "\0\u03a0\0\u03bd\0\u03da\0\u03f7\0\35\0\35\0\35\0\35"+
    "\0\u0414\0\u0431\0\u044e\0\u046b\0\u0488\0\u04a5\0\35\0\u04c2"+
    "\0\u04df\0\u04fc\0\35\0\35\0\u0519\0\u0536\0\35\0\35"+
    "\0\35\0\35\0\u0553\0\u0570\0\u058d\0\35\0\35";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\2"+
    "\1\11\10\2\1\12\7\2\1\13\1\14\1\15\37\0"+
    "\1\4\1\16\33\0\1\4\1\16\2\0\1\17\2\0"+
    "\1\20\1\0\1\21\2\0\1\22\1\23\2\0\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\0\1\32\5\0"+
    "\1\33\36\0\1\6\36\0\1\34\47\0\1\35\31\0"+
    "\1\36\1\37\24\0\1\40\34\0\1\41\41\0\1\42"+
    "\5\0\1\43\34\0\1\44\41\0\1\45\16\0\1\46"+
    "\10\0\1\47\22\0\1\50\31\0\1\51\6\0\1\52"+
    "\1\0\1\53\31\0\1\54\10\0\1\55\16\0\1\56"+
    "\56\0\1\57\6\0\1\33\3\0\1\17\2\0\1\20"+
    "\1\0\1\21\2\0\1\22\1\23\2\0\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\0\1\32\12\0\1\60"+
    "\32\0\1\61\36\0\1\62\40\0\1\63\26\0\1\64"+
    "\54\0\1\65\37\0\1\66\32\0\1\67\22\0\1\70"+
    "\27\0\1\71\35\0\1\72\33\0\1\73\37\0\1\74"+
    "\42\0\1\75\22\0\1\76\53\0\1\77\20\0\1\100"+
    "\30\0\1\101\42\0\1\102\35\0\1\103\1\104\42\0"+
    "\1\105\23\0\1\106\35\0\1\107\35\0\1\110\1\111"+
    "\33\0\1\112\27\0\1\113\32\0\1\114\42\0\1\115"+
    "\35\0\1\116\1\117\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1450];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\3\11\2\0\1\11\11\0\1\11"+
    "\1\1\6\0\3\11\1\0\6\11\3\0\1\11\5\0"+
    "\4\11\4\0\1\1\1\0\1\11\2\0\1\1\2\11"+
    "\2\0\4\11\2\0\1\1\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * number of newlines encountered up to the start of the matched text.
   * (Unused, consider deletion.)
   */
  @SuppressWarnings("unused")
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text. (Unused, consider deletion.)
   */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line.
   * (Unused, consider deletion.)
   */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed
   * (Unused, consider deletion.)
   */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	public PXTransformLexer()
	{
		this((Reader) null);
	}

	private PXTransformLexeme createLexeme(PXTransformTokenType type)
	{
		return createLexeme(type, yytext());
	}
	
	private PXTransformLexeme createLexeme(PXTransformTokenType type, Object value)
	{
		return new PXTransformLexeme(type, yychar, yylength(), value);
	}

	private PXDimension createDimension(String source, String units)
	{
		String numberString = source.substring(0, source.length() - units.length());
		
		return new PXDimension(Float.parseFloat(numberString), units);
	}

	public PXTransformLexeme nextLexeme()
	{
		PXTransformLexeme result = null;
		 
		try
		{
			result = yylex();
		} 
		catch (Exception e)
		{
			e.printStackTrace();
		}

		return result;
	}

	public void setSource(String source)
	{
		yyreset(new StringReader(source));
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PXTransformLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  PXTransformLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public PXTransformLexeme yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 34: 
          { return createLexeme(PXTransformTokenType.TRANSLATEY);
          }
        case 35: break;
        case 6: 
          { return createLexeme(PXTransformTokenType.COMMA);
          }
        case 36: break;
        case 10: 
          { return createLexeme(PXTransformTokenType.EMS, createDimension(yytext(), "em"));
          }
        case 37: break;
        case 24: 
          { return createLexeme(PXTransformTokenType.ANGLE, createDimension(yytext(), "grad"));
          }
        case 38: break;
        case 30: 
          { return createLexeme(PXTransformTokenType.SCALEY);
          }
        case 39: break;
        case 28: 
          { return createLexeme(PXTransformTokenType.ROTATE);
          }
        case 40: break;
        case 19: 
          { return createLexeme(PXTransformTokenType.ANGLE, createDimension(yytext(), "rad"));
          }
        case 41: break;
        case 32: 
          { return createLexeme(PXTransformTokenType.TRANSLATE);
          }
        case 42: break;
        case 15: 
          { return createLexeme(PXTransformTokenType.LENGTH, createDimension(yytext(), "pt"));
          }
        case 43: break;
        case 26: 
          { return createLexeme(PXTransformTokenType.SKEWX);
          }
        case 44: break;
        case 2: 
          { return createLexeme(PXTransformTokenType.NUMBER, Float.parseFloat(yytext()));
          }
        case 45: break;
        case 33: 
          { return createLexeme(PXTransformTokenType.TRANSLATEX);
          }
        case 46: break;
        case 12: 
          { return createLexeme(PXTransformTokenType.TIME, createDimension(yytext(), "ms"));
          }
        case 47: break;
        case 31: 
          { return createLexeme(PXTransformTokenType.MATRIX);
          }
        case 48: break;
        case 4: 
          { return createLexeme(PXTransformTokenType.LPAREN);
          }
        case 49: break;
        case 22: 
          { return createLexeme(PXTransformTokenType.LENGTH, createDimension(yytext(), "dpx"));
          }
        case 50: break;
        case 13: 
          { return createLexeme(PXTransformTokenType.LENGTH, createDimension(yytext(), "mm"));
          }
        case 51: break;
        case 20: 
          { return createLexeme(PXTransformTokenType.FREQUENCY, createDimension(yytext(), "kHz"));
          }
        case 52: break;
        case 1: 
          { return createLexeme(PXTransformTokenType.ERROR);
          }
        case 53: break;
        case 29: 
          { return createLexeme(PXTransformTokenType.SCALEX);
          }
        case 54: break;
        case 25: 
          { return createLexeme(PXTransformTokenType.SCALE);
          }
        case 55: break;
        case 9: 
          { return createLexeme(PXTransformTokenType.EXS, createDimension(yytext(), "ex"));
          }
        case 56: break;
        case 8: 
          { return createLexeme(PXTransformTokenType.PERCENTAGE, createDimension(yytext(), "%"));
          }
        case 57: break;
        case 14: 
          { return createLexeme(PXTransformTokenType.LENGTH, createDimension(yytext(), "in"));
          }
        case 58: break;
        case 16: 
          { return createLexeme(PXTransformTokenType.LENGTH, createDimension(yytext(), "px"));
          }
        case 59: break;
        case 17: 
          { return createLexeme(PXTransformTokenType.LENGTH, createDimension(yytext(), "pc"));
          }
        case 60: break;
        case 27: 
          { return createLexeme(PXTransformTokenType.SKEWY);
          }
        case 61: break;
        case 11: 
          { return createLexeme(PXTransformTokenType.LENGTH, createDimension(yytext(), "cm"));
          }
        case 62: break;
        case 18: 
          { return createLexeme(PXTransformTokenType.FREQUENCY, createDimension(yytext(), "Hz"));
          }
        case 63: break;
        case 23: 
          { return createLexeme(PXTransformTokenType.SKEW);
          }
        case 64: break;
        case 7: 
          { return createLexeme(PXTransformTokenType.TIME, createDimension(yytext(), "s"));
          }
        case 65: break;
        case 21: 
          { return createLexeme(PXTransformTokenType.ANGLE, createDimension(yytext(), "deg"));
          }
        case 66: break;
        case 3: 
          { /* ignore */
          }
        case 67: break;
        case 5: 
          { return createLexeme(PXTransformTokenType.RPAREN);
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	return new PXTransformLexeme(PXTransformTokenType.EOF, yychar, 0, "end-of-file");
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
